name: pipeline-08

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        run: echo "Run Build"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: echo "Run Test"